server:
  port: 8080

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://172.28.200.187:3306/eventuate?autoReconnect=true&useSSL=false
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 10000
  jpa:
    database: MYSQL
    generate-ddl: true 
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/customerservicedb}
    #zipkin:
    #discoveryClientEnabled: false
  #baseUrl: http://172.28.200.187:9411/
    #sender:
    #  type: web
 
eventuatelocal:
  kafka:
    bootstrap:
      servers: 172.28.200.187:9092
  zookeeper:
    connection:
      string: 172.28.200.187:2181
  cdc:
    dbUserName: root
    dbPassword: rootpassword

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: ERROR
      ordersample:
        customerservice: DEBUG
  file: /Users/cavendanoa/Documents/Carlos-Docs/order-processing-system/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
---  
spring:
  profiles: container
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      idle-timeout: ${SPRING_DATASOURCE_TIMEOUT}
  jpa:
    database: MYSQL
    generate-ddl: true
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://${MONGODB}}
    
eventuatelocal:
  kafka: 
    bootstrap:
      servers: ${EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS}
  zookeeper:
    connection:
      string: ${EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING}
  cdc:
    dbUserName: root
    dbPassword: rootpassword
