apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    nodePort: 32092
    targetPort: 9092
  selector:
    name: kafka
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kafka
          image: eventuateio/eventuateio-local-kafka:0.22.0.RELEASE
          env:
            - name: KAFKA_HEAP_OPTS
              value: -Xmx320m -Xms320m
            - name: ZOOKEEPER_SERVERS
              value: zookeeper:2181
          ports:
              - containerPort: 9092
          volumeMounts:
            - name: kafka-persistent-storage
              mountPath: /usr/local/kafka-data
            - name: kafka-config-volume
              mountPath: /usr/local/kafka-config2
      volumes:
      - name: kafka-config-volume
        configMap:
          name: kafka-config
  volumeClaimTemplates:
  - metadata:
      name: kafka-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
