apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  ports:
  - port: 3306
    nodePort: 32306
    targetPort: 3306
  selector:
    name: mysql
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: eventuateio/eventuate-tram-sagas-mysql:0.11.0.RELEASE
          imagePullPolicy: Always
          args:
              - "--ignore-db-dir=lost+found"
          ports:
              - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: mysql_root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: mysql_password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
