server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://172.28.112.191:3306/eventuate?autoReconnect=true&useSSL=false
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 10000
  jpa:
    database: MYSQL
    generate-ddl: true
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/orderservicedb}

eventuatelocal:
  kafka:
    bootstrap:
      servers: 172.28.112.191:9092
  zookeeper:
    connection:
      string: 172.28.112.191:2181
  cdc:
    dbUserName: root
    dbPassword: rootpassword

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true